apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: app2
  name: app2-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: app2
  template: 
    metadata: 
      labels: 
        app: app2
    spec:
      containers:        
        - image: vilchesplus/notifier
          name: app2
          ports:
           - containerPort: 5001
           
           