apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: script
  name: script-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: script
  template: 
    metadata: 
      labels: 
        app: script
    spec:
      containers: 
        - image: vilchesplus/web-scraper-telegram-bot
          name: script-1
          ports:
           - containerPort: 5000
        - image: vilchesplus/notifier
          name: script-2
          ports:
           - containerPort: 5001
           
           